export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL'
export const LOGOUT = 'LOGOUT'
export const FETCH_REQUEST_AUTH = 'FETCH_REQUEST_AUTH';
export const FETCH_SUCCESS_AUTH = 'FETCH_SUCCESS_AUTH';
export const FETCH_ERROR_AUTH = 'FETCH_ERROR_AUTH';